server {
	listen 80;

	# to reconsider:
	server_name ckk.lt;

	# also to think about - must I use the vps nginx config? Use docker somehow?
	root /usr/share/nginx/html;

	index index.html;

	location / {
		try_files $uri $uri/ /index.html;
	}
	location /api/ {
		# Connects frontend to api service when browsing through nginx's autoindex
		   proxy_pass http://api:8000; 
		   proxy_set_header Host $host;
	       }
}


	
