server {
	listen 80;

	# to reconsider:
	server_name localhost;



	location / {
		   proxy_pass http://api:8000; 
		   proxy_set_header Host $host;
		   proxy_set_header X-Real-IP $remote_addr;
		   proxy_pass_header X-Scrub-Log;
		   add_header 'Access-Control-Expose-Headers' 'X-Scrub-Log' always;
	}
	location /api/ {
		   proxy_pass http://api:8000; 
		   proxy_set_header Host $host;
		   client_max_body_size 150M;
		   proxy_pass_header X-Scrub-Log;
		   add_header 'Access-Control-Expose-Headers' 'X-Scrub-Log' always;
	       }
}


	
