services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: scrubber_db
      BAU_DB_USER: ${BAU_DB_USER}
      BAU_DB_PASSWORD: ${BAU_DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - /home/karol/photo_scrubber/db/procedures:/procedures
      - /home/karol/photo_scrubber/db/scripts:/docker-entrypoint-initdb.d/
    restart: always
    
  db-init:
    image: postgres:15-alpine
    depends_on:
      - db
    volumes:
      - /home/karol/photo_scrubber/db/procedures:/procedures
    environment:
      - PGPASSWORD=${DB_PASSWORD}
    command: sh -c "for f in /procedures/*.sql; do psql -h db -U ${DB_USER} -d scrubber_db -f \"\$$f\"; done"

    # I use restart to avoid making a custom detector for db readiness, but hopefully there's a more elegant way of getting procedures imported.
    restart: on-failure


  api:
    build: ./backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment: 
     DATABASE_URL: postgresql://${BAU_DB_USER}:${BAU_DB_PASSWORD}@db:5432/scrubber_db
    volumes:
      - /home/karol/photo_scrubber/backend:/app
    restart: always

  gateway:
    image: nginx:alpine
    ports:
      - "8080:80"
    depends_on:
      - api
    volumes:
      - /home/karol/photo_scrubber/frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - /home/karol/photo_scrubber/frontend:/usr/share/nginx/html
    restart: always


volumes:
  pgdata:
